/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.secretary;

import dao.MedicalFolderDao;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.util.Rotation;

/**
 *
 * @author bynan
 */
public class Chart extends javax.swing.JInternalFrame {

    /**
     * Creates new form Dashboard
     */
    public Chart() {
        initComponents();
    }

    public Chart(String applicationTitle, String chartTitle) {
        super(applicationTitle);
// This will create the dataset
        PieDataset dataset = createDataset();
// based on the dataset we create the chart
        JFreeChart chart = createChart(dataset, chartTitle);
// we put the chart into a panel
        ChartPanel chartPanel = new ChartPanel(chart);
// default size
        chartPanel.setPreferredSize(new java.awt.Dimension(500, 270));
// add it to our application
        setContentPane(chartPanel);
        setClosable(true);
        chartPanel.setBounds(100, 100, 347, 236);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setAlignmentX(20.0F);
        setAlignmentY(20.0F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
     private static final long serialVersionUID = 1L;

    /**
     * Creates a sample data set
     */
    private PieDataset createDataset() {
        DefaultPieDataset result = new DefaultPieDataset();
        MedicalFolderDao med = new MedicalFolderDao();
        //generalist
        int gen = med.selectNumberOfPatientsPerDoctor(3);
        //radiologist
        int rad = med.selectNumberOfPatientsPerDoctor(4);
        //dentist
        int den = med.selectNumberOfPatientsPerDoctor(5);

        result.setValue("Généraliste", gen);
        result.setValue("Radiologue", rad);
        result.setValue("Dentiste", den);
        return result;
    }

    /**
     * Creates a chart
     */
    private JFreeChart createChart(PieDataset dataset, String title) {
        JFreeChart chart = ChartFactory.createPieChart3D(
                title, // chart title
                dataset, // data
                true, // include legend
                true,
                false
        );
        PiePlot3D plot = (PiePlot3D) chart.getPlot();
        plot.setStartAngle(290);
        plot.setDirection(Rotation.CLOCKWISE);
        plot.setForegroundAlpha(0.5f);
        return chart;
    }
}
